stages:
  - test
  - build
  - release
  - deploy

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  DOCKER_TLS_CERTDIR: ""

include:
  - template: Security/SAST.gitlab-ci.yml

nodejs-scan-sast:
  tags:
    - yc-runner

semgrep-sast:
  tags:
    - yc-runner

build_frontend:
  stage: build
  image: docker:20-dind
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $YC_REGISTRY_LOGIN -p $YC_OAUTH_TOKEN $YC_REGISTRY
  script:
    - docker build --build-arg VERSION=$VERSION -t $YC_REGISTRY_NAME/momo-store-frontend:$CI_COMMIT_SHA -f frontend/Dockerfile .
    - docker push $YC_REGISTRY_NAME/momo-store-frontend:$CI_COMMIT_SHA
  # only:
  #    changes:
  #      - frontend/*
  tags:
    - yc-runner

build_backend: 
  stage: build
  image: docker:20-dind
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $YC_REGISTRY_LOGIN -p $YC_OAUTH_TOKEN $YC_REGISTRY
  script:
    - docker build --build-arg VERSION=$VERSION -t $YC_REGISTRY_NAME/momo-store-backend:$CI_COMMIT_SHA -f backend/Dockerfile .
    - docker push $YC_REGISTRY_NAME/momo-store-backend:$CI_COMMIT_SHA
  # only:
  #    changes:
  #      - backend/*
  tags:
    - yc-runner

upload_frontend_latest:
  stage: release
  image: docker:20-dind
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $YC_REGISTRY_LOGIN -p $YC_OAUTH_TOKEN $YC_REGISTRY
  script:
    - docker pull $YC_REGISTRY_NAME/momo-store-frontend:$CI_COMMIT_SHA
    - docker tag $YC_REGISTRY_NAME/momo-store-frontend:$CI_COMMIT_SHA $YC_REGISTRY_NAME/momo-store-frontend:latest
    - docker push $YC_REGISTRY_NAME/momo-store-frontend:latest
  # only:
  #    changes:
  #      - frontend/*
  tags:
    - yc-runner

upload_backend_latest:
  stage: release
  image: docker:20-dind
  before_script:
     - until docker info; do sleep 1; done
     - docker login -u $YC_REGISTRY_LOGIN -p $YC_OAUTH_TOKEN $YC_REGISTRY
  script:
    - docker pull $YC_REGISTRY_NAME/momo-store-backend:$CI_COMMIT_SHA
    - docker tag $YC_REGISTRY_NAME/momo-store-backend:$CI_COMMIT_SHA $YC_REGISTRY_NAME/momo-store-backend:latest
    - docker push $YC_REGISTRY_NAME/momo-store-backend:latest
  # only:
  #    changes:
  #      - backend/*
  tags:
    - yc-runner

deploy_helm_chart:
  stage: deploy
  image: alpine/k8s:1.24.12
  before_script:
    - helm registry login $YC_REGISTRY -u $YC_REGISTRY_LOGIN -p $YC_OAUTH_TOKEN
  script:
    - rm -rf /root/.kube
    - mkdir -p /root/.kube
    - cp "$kube_ca_pem" /root/ca.pem
    - export MASTER_ENDPOINT=${MASTER_ENDPOINT}
    - export SA_TOKEN=${SA_TOKEN}
    - kubectl config set-cluster sa-test2 --certificate-authority=/root/ca.pem --server=$MASTER_ENDPOINT --kubeconfig=/root/.kube/config
    - kubectl config set-credentials admin-user --token=$SA_TOKEN --kubeconfig=/root/.kube/config
    - kubectl config set-context default --cluster=sa-test2 --user=admin-user --kubeconfig=/root/.kube/config
    - kubectl config use-context default --kubeconfig=/root/.kube/config
    - helm pull ${CHART_REGISTRY_URL}/${CHART_NAME} --version ${CHART_VERSION}
    - tar -zxvf ${CHART_NAME}-${CHART_VERSION}.tgz
    - helm install ${CHART_NAME} ${CHART_NAME} || helm upgrade ${CHART_NAME} ${CHART_NAME} -n ${NAMESPACE}
  # only:
  #    changes:
  #      - backend/*
  #      - frontend/*
  tags:
    - yc-runner
     


