---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: momo-store-frontend-{{ .Release.Name }}
  namespace: vp-namespace
  labels:
    app.kubernetes.io/name: momo-store-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: momo-store-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: momo-store-frontend
    spec:
      containers:
        - image: "{{ .Values.image }}:{{ .Values.image_tag }}"
          name: "{{ .Values.container_name }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          ports:
            - containerPort: {{ .Values.container_port }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      imagePullSecrets:
        - name: docker-config-secret-front
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf

