---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: momo-store-frontend
  namespace: vp-namespace
  labels:
    app.kubernetes.io/name: momo-store-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: momo-store-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: momo-store-frontend
    spec:
      containers:
        - image: cr.yandex/crppqvt1dfahv0keoq97/momo-store-frontend:latest
          name: momo-store-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: docker-config-secret-front
