---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: momo-frontend-ingress
  namespace: vp-namespace
spec:
  tls:
    - hosts:
      - "{{ .Values.ingress_fqdn }}"
      secretName: k8s-secret
  ingressClassName: "nginx"
  rules:
  - host: "{{ .Values.ingress_fqdn }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.frontend_service_name }}"
            port:
              number: 8080