---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: momo-store-backend
  namespace: vp-namespace
  labels:
    app.kubernetes.io/name: momo-store-backend
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: "20%"
  selector:
    matchLabels:
      app.kubernetes.io/name: momo-store-backend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: momo-store-backend
    spec:
      containers:
        - image: cr.yandex/crppqvt1dfahv0keoq97/momo-store-backend:latest
          name: momo-store-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
      imagePullSecrets:
        - name: docker-config-secret
