---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: momo-store-backend-{{ .Release.Name }}
  namespace: vp-namespace
  labels:
    app.kubernetes.io/name: momo-store-backend
spec:
  strategy:
    type: "{{ .Values.strategy_type }}"
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: "20%"
  selector:
    matchLabels:
      app.kubernetes.io/name: momo-store-backend
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: momo-store-backend
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - image: "{{ .Values.image }}:{{ .Values.image_tag }}"
          name: "{{ .Values.container_name }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          ports:
            - containerPort: {{ .Values.container_port }}
          livenessProbe:
            httpGet:
              path: /products
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 6
      imagePullSecrets:
        - name: docker-config-secret
