---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: momo-store-backend-{{ .Release.Name }}
  namespace: vp-namespace
  labels:
    app.kubernetes.io/name: momo-store-backend
spec:
  strategy:
    type: "{{ .Values.strategy_type }}"
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: "20%"
  selector:
    matchLabels:
      app.kubernetes.io/name: momo-store-backend
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: momo-store-backend
    spec:
      containers:
        - image: "{{ .Values.image }}:{{ .Values.image_tag }}"
          name: "{{ .Values.container_name }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          ports:
            - containerPort: {{ .Values.container_port }}
      imagePullSecrets:
        - name: docker-config-secret
