apiVersion: v1
kind: Service
metadata:
  name: momo-backend-service
  namespace: vp-namespace
  labels:
    app.kubernetes.io/name: momo-store-backend
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/name: momo-store-backend
